### ISSUE TITLE
Asking about codes license

### ISSUE THREAD

**Issue by heybran** [humanmade/hm-table-of-contents-plugin#11]
Hello HM team,

Sorry about opening this issue. I folked the repo without realizing that this project doesn't have a license yet. My original thought is to modify some codes to be used on my personal blog. I don't think I am allowed to do that now given that this plugin doesn't have a license?

**Comment by rmccue** [comment]
Hi @heybran, as with all WordPress plugins, this is licensed under the GPL v2 or later, so you're welcome to use and modify it :)

**Comment by heybran** [comment]
Hi @rmccue, thank you so much for clarifying that. I will close this issue now.
